"""Create client and bot tables v3

Revision ID: 0fa15635321e
Revises: 027e976b566e
Create Date: 2025-08-31 17:25:05.149645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa15635321e'
down_revision: Union[str, Sequence[str], None] = '027e976b566e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('language_preference', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('telegram_token', sa.String(), nullable=False),
    sa.Column('knowledge_base_uz', sa.Text(), nullable=True),
    sa.Column('knowledge_base_ru', sa.Text(), nullable=True),
    sa.Column('knowledge_base_en', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('TRIAL', 'ACTIVE', 'INACTIVE', name='botstatus'), nullable=False),
    sa.Column('plan_type', sa.Enum('TRIAL', 'MONTHLY', 'YEARLY', name='plantype'), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('default_language', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bots_telegram_token'), 'bots', ['telegram_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bots_telegram_token'), table_name='bots')
    op.drop_table('bots')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
